import { Button } from "@/components/Button";
import { Card } from "@/components/Card";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { SectionHeading } from "@/components/SectionHeading";
import { Tag } from "@/components/Tag";
import type { IconType } from "react-icons";
import { FaBrain, FaCode, FaCubes, FaDatabase, FaGithub, FaHtml5, FaJava, FaJsSquare, FaLaptopCode, FaNetworkWired, FaNodeJs, FaPython, FaReact, FaTools } from "react-icons/fa";
import { SiCss, SiExpress, SiGooglecolab, SiJupyter, SiLeetcode, SiMysql, SiPostgresql } from "react-icons/si";

type SkillGroup = { name: string; icon: IconType; skills: [string, IconType][] };

const skillGroups: SkillGroup[] = [
  { name: "Programming Languages", icon: FaCode, skills: [["Java", FaJava], ["Python", FaPython], ["C", FaCode]] },
  { name: "Web Technologies", icon: FaLaptopCode, skills: [["HTML", FaHtml5], ["CSS", SiCss], ["JavaScript", FaJsSquare], ["ReactJS", FaReact], ["ExpressJS", SiExpress], ["NodeJS", FaNodeJs]] },
  { name: "Databases", icon: FaDatabase, skills: [["MySQL", SiMysql], ["PostgreSQL", SiPostgresql]] },
  { name: "Tools", icon: FaTools, skills: [["GitHub", FaGithub], ["Jupyter Notebook", SiJupyter], ["VS Code", FaCode], ["Google Colab", SiGooglecolab]] },
  { name: "Core Concepts", icon: FaCubes, skills: [["Object-Oriented Programming", FaCubes], ["Data Structures and Algorithms", FaCode], ["DBMS", FaDatabase], ["Operating Systems", FaLaptopCode], ["Software Engineering", FaTools], ["Artificial Intelligence", FaBrain], ["Computer Networks", FaNetworkWired]] },
];

const projects = [
  { name: "ExamGaurd-AI-Proctoring-System", image: "/project-images/examguard.png", github: "https://github.com/Namratha18-hub/ExamGuard-AI-Proctoring-System", description: "An AI-based online proctoring system with real-time face detection, activity monitoring, integrity scoring, and a dashboard for risk analytics and reports.", stack: ["AI", "Streamlit", "JSON/CSV"], featured: true },
  { name: "SocialPilot", image: "/project-images/socialpilot.png", github: "https://github.com/Namratha18-hub/SocialPilot", description: "A full-stack social media platform with OAuth-based publishing across Instagram, LinkedIn, and YouTube, plus Campaign, Analytics, and Reports modules.", stack: ["Next.js", "FastAPI", "PostgreSQL", "Celery"], featured: true },
  { name: "Socil-Media-Platform", image: "/project-images/social-media-platform.png", github: "https://github.com/Namratha18-hub/Social-Media-Platform", description: "A social media platform designed to provide users with an interactive space to create, share, and engage with content.", stack: ["ReactJS", "Node.js", "Express.js", "MongoDB"] },
  { name: "Simple-E-Commerece-Store", image: "/project-images/ecommerce.png", github: "https://github.com/Namratha18-hub/Simple-E-commerce-Store", description: "A responsive e-commerce web application featuring product browsing, shopping functionality, and a user-friendly online store experience.", stack: ["HTML", "CSS", "JavaScript", "Node.js", "Express.js", "MongoDB"] },
  { name: "Bluewave-cafe-web", image: "/project-images/bluewave-cafe.png", github: "https://github.com/Namratha18-hub/bluewave-cafe-web", description: "A full-stack BlueWave Web Café application with responsive UI, backend functionality, database integration, and core web features.", stack: ["Full-stack", "Responsive UI", "Database integration"] },
  { name: "client-lead-manager", image: "/project-images/client-lead-manager.png", github: "https://github.com/Namratha18-hub/client-lead-manager", description: "A web-based client and lead management application for organizing client information, tracking leads, and managing business interactions.", stack: ["ReactJS", "Node.js", "Express.js", "MongoDB"] },
  { name: "quiz-web-app-js", image: "/project-images/quiz-app.png", github: "https://github.com/Namratha18-hub/quiz-web-app-js", description: "A responsive quiz web application built with HTML, CSS, and JavaScript, featuring interactive questions, answer selection, and score calculation.", stack: ["HTML", "CSS", "JavaScript"] },
];

const certificates = [
  { issuer: "NPTEL", name: "DBMS", url: "/certificates/nptel-dbms.pdf" },
  { issuer: "GeeksforGeeks", name: "Java Skill Up", url: "/certificates/gfg-java-skill-up.pdf" },
  { issuer: "GeeksforGeeks", name: "60 Days POTD Challenge", url: "/certificates/gfg-60-days-potd.pdf" },
  { issuer: "CampusCrew", name: "India's Biggest AI Quiz", url: "/certificates/campuscrew-ai-quiz.pdf" },
  { issuer: "TCS iON Career Edge", name: "Interview Job Readiness", url: "/certificates/tcs-interview-job-readiness.pdf" },
  { issuer: "Simplilearn", name: "Introduction to Generative AI Studio", url: "/certificates/simplilearn-generative-ai-studio.pdf" },
  { issuer: "Cisco", name: "Data Analytics Essentials", url: "/certificates/cisco-data-analytics-essentials.pdf" },
  { issuer: "Cisco", name: "Cyber Threat Management", url: "/certificates/cisco-cyber-threat-management.pdf" },
  { issuer: "Cisco", name: "C++ Essentials 1", url: "/certificates/cisco-cpp-essentials-1.pdf" },
  { issuer: "Cisco", name: "Python Essentials 1", url: "/certificates/cisco-python-essentials-1.pdf" },
  { issuer: "Cisco", name: "Python Essentials 2", url: "/certificates/cisco-python-essentials-2.pdf" },
  { issuer: "Infosys", name: "Introduction to Python", url: "/certificates/infosys-introduction-to-python.pdf" },
  { issuer: "Infosys", name: "Basics of Python", url: "/certificates/infosys-basics-of-python.pdf" },
  { issuer: "Infosys", name: "DBMS Part 1", url: "/certificates/infosys-dbms-part-1.pdf" },
  { issuer: "Infosys", name: "DBMS Part 2", url: "/certificates/infosys-dbms-part-2.pdf" },
  { issuer: "Infosys", name: "Object Oriented Programming using Python", url: "/certificates/infosys-oop-python.pdf" },
  { issuer: "Infosys", name: "Programming Fundamentals using Python Part 1", url: "/certificates/infosys-programming-fundamentals-part-1.pdf" },
  { issuer: "Infosys", name: "Programming Fundamentals using Python Part 2", url: "/certificates/infosys-programming-fundamentals-part-2.pdf" },
  { issuer: "Infosys", name: "Introduction to NoSQL Databases", url: "/certificates/infosys-introduction-nosql-databases.pdf" },
  { issuer: "Infosys", name: "Python Foundation", url: "/certificates/infosys-python-foundation.pdf" },
  { issuer: "Infosys", name: "Software Engineering and Agile Software Development", url: "/certificates/infosys-software-engineering-agile.pdf" },
  { issuer: "Infosys", name: "Agile Scrum in Practice", url: "/certificates/infosys-agile-scrum.pdf" },
  { issuer: "Future Interns", name: "Full Stack Web Development", url: "/certificates/future-interns-full-stack-web-development.pdf" },
  { issuer: "Google", name: "Music Night Edition", url: "/certificates/google-music-night-edition.pdf" },
  { issuer: "Virtual Internship", name: "Gen AI", url: "/certificates/virtual-internship-gen-ai.pdf" },
  { issuer: "Virtual Internship", name: "AIML", url: "/certificates/virtual-internship-aiml.pdf" },
  { issuer: "AICTE", name: "AICTE", url: "/certificates/aicte.pdf" },
  { issuer: "AWS", name: "Gen AI Foundations", url: "/certificates/aws-gen-ai-foundations.pdf" },
  { issuer: "AWS", name: "ML for NLP", url: "/certificates/aws-ml-for-nlp.pdf" },
  { issuer: "AWS", name: "ML Foundations", url: "/certificates/aws-ml-foundations.pdf" },
  { issuer: "Cambridge English", name: "Qualification (Level-3)", url: "/certificates/cambridge_level-3.pdf" },
  { issuer: "NSPC", name: "NSPC-2026", url: "/certificates/NSPC-2026.pdf" },
];

export default function Home() {
  return <main>
    <header className="hero" id="home"><Navbar /><div className="hero-inner"><div className="hero-copy"><p className="eyebrow hero-eyebrow">Computer Science &amp; Engineering <span className="eyebrow-dot" aria-hidden="true" /></p><h1>Namratha<br /><span>Sanapala</span></h1><p className="hero-lede">Computer Science and Engineering undergraduate with a strong foundation in programming, data structures and algorithms, and software development. Experienced in building academic and software projects using Java, Python, DBMS, computer networks, and modern web technologies. Seeking a Software Development Internship to apply technical expertise, strengthen industry experience, and contribute to meaningful real-world applications.</p><div className="hero-actions"><Button href="#projects">View Projects <span aria-hidden="true">↗</span></Button><Button href="#contact" variant="secondary">Contact Me <span aria-hidden="true">✉</span></Button><Button href="https://github.com/Namratha18-hub" variant="text" target="_blank" rel="noopener noreferrer">GitHub <span aria-hidden="true">↗</span></Button><Button href="/resume" variant="text" target="_blank" rel="noopener noreferrer">View Resume <span aria-hidden="true">↗</span></Button></div><div className="social-links" aria-label="Social links"><a href="https://github.com/Namratha18-hub" target="_blank" rel="noopener noreferrer" aria-label="GitHub">●</a><a href="https://www.linkedin.com/in/namratha-sanapala" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">in</a><a href="https://leetcode.com/u/Namratha_18" target="_blank" rel="noopener noreferrer" aria-label="LeetCode"><SiLeetcode aria-hidden="true" /></a><a href="mailto:sanapalanamratha79@gmail.com" aria-label="Email">✉</a></div></div><div className="photo-placeholder" aria-label="Profile photo"><div className="photo-frame"><img src="/profile.jpeg" alt="Namratha Sanapala" /></div></div></div><div className="hero-metrics" aria-label="Resume highlights"><div><span className="metric-icon">⌂</span><p>CGPA</p><strong>9.62</strong></div><div><span className="metric-icon">▣</span><p>Education</p><strong>B.Tech CSE</strong></div><div><span className="metric-icon">▤</span><p>Experience</p><strong>2 Internships</strong></div><div><span className="metric-icon">&lt;/&gt;</span><p>DSA Problems</p><strong>60+ Solved</strong></div></div></header>
    <section className="section" id="about"><SectionHeading eyebrow="01 / About" title="Curious by nature. Grounded in code." /><div className="about-grid"><div className="about-intro"><p className="about-lede">Computer Science and Engineering undergraduate with a strong foundation in programming, data structures and algorithms, and software development.</p><p className="about-body">Computer Science and Engineering undergraduate with a strong foundation in programming, data structures and algorithms, and software development. Experienced in building academic and software projects using Java, Python, DBMS, computer networks, and modern web technologies. Seeking a Software Development Internship to apply technical expertise, strengthen industry experience, and contribute to meaningful real-world applications.</p></div><div className="about-facts"><Card><span className="fact-icon">▣</span><div><p className="label">Degree</p><strong>B.Tech CSE</strong></div></Card><Card><span className="fact-icon">⌂</span><div><p className="label">College</p><strong>SRKREC</strong></div></Card><Card><span className="fact-icon">◷</span><div><p className="label">Duration</p><strong>2024–2028</strong></div></Card><Card><span className="fact-icon">★</span><div><p className="label">Academic performance</p><strong>CGPA 9.62</strong></div></Card></div></div></section>
    <section className="section section-muted" id="skills"><SectionHeading eyebrow="02 / Skills" title="A practical technical toolkit." description="Technologies and concepts used across academic and software projects." /><div className="skills-grid">{skillGroups.map((group) => { const CategoryIcon = group.icon; return <Card className="skill-card" key={group.name}><div className="skill-card-heading"><span className="skill-icon"><CategoryIcon aria-hidden="true" /></span><h3>{group.name}</h3></div><div className="skill-tile-grid">{group.skills.map(([skill, SkillIcon]) => <div className="skill-tile" key={skill}><SkillIcon aria-hidden="true" /><span>{skill}</span></div>)}</div></Card>; })}</div></section>
    <section className="section projects-section" id="projects"><SectionHeading eyebrow="03 / Projects" title="Selected work." description="A selection of academic and software projects built with practical engineering skills." /><div className="projects-grid">{projects.map((project, index) => <Card className={`project-card${project.featured ? " project-card-featured" : ""}`} key={project.name}><div className="project-image">{project.image ? <img src={project.image} alt={`${project.name} project screenshot`} loading="lazy" /> : <span>Screenshot unavailable</span>}<b>{String(index + 1).padStart(2, "0")}</b></div><div className="project-content"><h3>{project.name}</h3><p>{project.description}</p><div className="tag-list">{project.stack.map((technology) => <Tag key={technology}>{technology}</Tag>)}</div><div className="project-actions"><a className="button-secondary" href={project.github} target="_blank" rel="noopener noreferrer">GitHub <span aria-hidden="true">↗</span></a></div></div></Card>)}</div></section>
    <section className="section section-muted" id="experience"><SectionHeading eyebrow="04 / Experience" title="Experience." /><div className="timeline"><Card><p className="label">June 2026 — August 2026 · Remote</p><h3>Infosys SpringBoard Internship 7.0</h3><ul><li>Completed the Infosys SpringBoard Internship 7.0, gaining hands-on experience in software development and emerging technologies.</li><li>Applied programming and problem-solving skills through practical learning, projects, and industry-oriented tasks.</li></ul></Card><Card><p className="label">March 2026 — April 2026 · Remote</p><h3>Future Interns</h3><ul><li>Worked on full-stack web development involving both frontend and backend technologies.</li><li>Gained hands-on experience in building and deploying web applications while improving problem-solving skills.</li></ul></Card></div></section>
    <section className="section" id="education"><SectionHeading eyebrow="05 / Education" title="Education." /><div className="education-row"><span className="education-icon" aria-hidden="true">▣</span><div><h3>Sagi Rama Krishnam Raju Engineering College (SRKREC)</h3><p>B.Tech in Computer Science and Engineering <span className="education-separator">·</span> 2024–2028</p></div><strong><span>9.62</span><small>CGPA</small></strong></div><div className="education-row"><span className="education-icon" aria-hidden="true">⌂</span><div><h3>Sri Chaitanya Junior College</h3><p>Intermediate (MPC) <span className="education-separator">·</span> 2022–2024</p></div><strong><span>96.5%</span><small>Percentage</small></strong></div><div className="education-row"><span className="education-icon" aria-hidden="true">⌂</span><div><h3>RCM St Anthony&apos;s English Medium High School</h3><p>State Board of Secondary Education, Andhra Pradesh</p></div><strong><span>90.44%</span><small>Percentage</small></strong></div></section>
    <section className="section section-muted" id="certifications"><SectionHeading eyebrow="06 / Certifications" title="Credentials and continuous learning." description="A collection of certificates earned across software development, data, AI, and professional learning." /><div className="certificate-grid">{certificates.map((certificate) => <Card className="certificate-card" key={`${certificate.issuer}-${certificate.name}`}><span className="certificate-icon">✓</span><div><p className="certificate-issuer">{certificate.issuer}</p><h3>{certificate.name}</h3><a className="certificate-link" href={certificate.url} target="_blank" rel="noopener noreferrer">View Certificate</a></div></Card>)}</div></section>
    <section className="section" id="achievements"><SectionHeading eyebrow="07 / Achievements" title="Milestones so far." /><div className="achievement-grid"><Card className="achievement-card"><span className="achievement-icon">&lt;/&gt;</span><strong>60+</strong><p>Solved DSA problems on GeeksforGeeks.</p></Card><Card className="achievement-card"><span className="achievement-icon">★</span><strong>9.6+</strong><p>Maintained a CGPA above 9.6 in B.Tech CSE.</p></Card><Card className="achievement-card"><span className="achievement-icon">◇</span><strong>Multiple</strong><p>Completed AICTE virtual internships.</p></Card><Card className="achievement-card"><span className="achievement-icon">▣</span><strong>Multiple</strong><p>Completed academic and full-stack development projects.</p></Card></div></section>
    <section className="contact-section" id="contact"><div className="contact-inner"><div className="contact-grid"><div className="contact-details"><SectionHeading eyebrow="08 / Contact" title="Let’s build something useful." description="For internship opportunities and professional collaboration, reach out by email or connect through my professional profiles." /><div className="contact-info"><a href="mailto:sanapalanamratha79@gmail.com"><span className="contact-icon">✉</span><span><small>Email</small><strong>sanapalanamratha79@gmail.com</strong></span></a><a href="tel:+919490694589"><span className="contact-icon">⌕</span><span><small>Phone</small><strong>+91 9490694589</strong></span></a></div><div className="contact-socials"><a href="https://github.com/Namratha18-hub" target="_blank" rel="noopener noreferrer">GitHub <span aria-hidden="true">↗</span></a><a href="https://www.linkedin.com/in/namratha-sanapala" target="_blank" rel="noopener noreferrer">LinkedIn</a></div></div><Card className="contact-form-card"><h3>Send a message</h3><p>Share a little about the opportunity or collaboration.</p><form><label htmlFor="name">Name</label><input id="name" name="name" type="text" placeholder="Your name" /><label htmlFor="email">Email</label><input id="email" name="email" type="email" placeholder="you@example.com" /><label htmlFor="message">Message</label><textarea id="message" name="message" rows={5} placeholder="Your message" /><button className="button-primary" type="submit">Send Message <span aria-hidden="true">↗</span></button></form></Card></div></div></section><Footer />
  </main>;
}
